name: shohaara
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
   
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.4.0
  slide_to_act: ^2.0.1
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  cloud_firestore: ^4.8.4
  firebase_storage: ^11.2.5
  fluttericon: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: A.Ali_banner3az.ir
      fonts:
        - asset: fonts/A.Ali_banner3az.ir.ttf

    - family: Vazir
      fonts:
        - asset: fonts/static/Vazirmatn-Bold.ttf
          weight: 700
        - asset: fonts/static/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: fonts/static/Vazirmatn-Medium.ttf
          weight: 500
        - asset: fonts/static/Vazirmatn-Regular.ttf
          weight: 400
        - asset: fonts/static/Vazirmatn-Light.ttf
          weight: 300
